security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: "$2y$13$DFayVLa5NZQSavmRjRVbduZzrmdXu5owceSK3LEb5M.LcB0EN4IsS" #Pass 'Lester123'
                        roles: ["ROLE_ADMIN"]
                    user:
                        password: "$2y$13$QMt6A.TBAf9X7QwTg8d9w.l57o4apktvt9vn4HrBzWCEgsLwBrIWa" #Pass 'Gwapo123'
                        roles: ["ROLE_USER"]

    firewalls:
        dev:
            pattern: ^/(?:_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: in_memory
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: app_home

    access_control:
        - { path: ^/dashboard, roles: [ROLE_USER, ROLE_ADMIN] }
